// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: body.proto

package proto;

public final class Body {
  private Body() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HumansFinalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HumansFinal)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Human body = 1;</code>
     */
    java.util.List<proto.Body.Human> 
        getBodyList();
    /**
     * <code>repeated .Human body = 1;</code>
     */
    proto.Body.Human getBody(int index);
    /**
     * <code>repeated .Human body = 1;</code>
     */
    int getBodyCount();
    /**
     * <code>repeated .Human body = 1;</code>
     */
    java.util.List<? extends proto.Body.HumanOrBuilder> 
        getBodyOrBuilderList();
    /**
     * <code>repeated .Human body = 1;</code>
     */
    proto.Body.HumanOrBuilder getBodyOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HumansFinal}
   */
  public static final class HumansFinal extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:HumansFinal)
      HumansFinalOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HumansFinal.newBuilder() to construct.
    private HumansFinal(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HumansFinal() {
      body_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HumansFinal();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HumansFinal(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                body_ = new java.util.ArrayList<proto.Body.Human>();
                mutable_bitField0_ |= 0x00000001;
              }
              body_.add(
                  input.readMessage(proto.Body.Human.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          body_ = java.util.Collections.unmodifiableList(body_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Body.internal_static_HumansFinal_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Body.internal_static_HumansFinal_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Body.HumansFinal.class, proto.Body.HumansFinal.Builder.class);
    }

    public static final int BODY_FIELD_NUMBER = 1;
    private java.util.List<proto.Body.Human> body_;
    /**
     * <code>repeated .Human body = 1;</code>
     */
    @java.lang.Override
    public java.util.List<proto.Body.Human> getBodyList() {
      return body_;
    }
    /**
     * <code>repeated .Human body = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends proto.Body.HumanOrBuilder> 
        getBodyOrBuilderList() {
      return body_;
    }
    /**
     * <code>repeated .Human body = 1;</code>
     */
    @java.lang.Override
    public int getBodyCount() {
      return body_.size();
    }
    /**
     * <code>repeated .Human body = 1;</code>
     */
    @java.lang.Override
    public proto.Body.Human getBody(int index) {
      return body_.get(index);
    }
    /**
     * <code>repeated .Human body = 1;</code>
     */
    @java.lang.Override
    public proto.Body.HumanOrBuilder getBodyOrBuilder(
        int index) {
      return body_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < body_.size(); i++) {
        output.writeMessage(1, body_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < body_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, body_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Body.HumansFinal)) {
        return super.equals(obj);
      }
      proto.Body.HumansFinal other = (proto.Body.HumansFinal) obj;

      if (!getBodyList()
          .equals(other.getBodyList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getBodyCount() > 0) {
        hash = (37 * hash) + BODY_FIELD_NUMBER;
        hash = (53 * hash) + getBodyList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Body.HumansFinal parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Body.HumansFinal parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Body.HumansFinal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Body.HumansFinal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Body.HumansFinal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Body.HumansFinal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Body.HumansFinal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Body.HumansFinal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Body.HumansFinal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Body.HumansFinal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Body.HumansFinal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Body.HumansFinal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Body.HumansFinal prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HumansFinal}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HumansFinal)
        proto.Body.HumansFinalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Body.internal_static_HumansFinal_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Body.internal_static_HumansFinal_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Body.HumansFinal.class, proto.Body.HumansFinal.Builder.class);
      }

      // Construct using proto.Body.HumansFinal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBodyFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          bodyBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Body.internal_static_HumansFinal_descriptor;
      }

      @java.lang.Override
      public proto.Body.HumansFinal getDefaultInstanceForType() {
        return proto.Body.HumansFinal.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Body.HumansFinal build() {
        proto.Body.HumansFinal result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Body.HumansFinal buildPartial() {
        proto.Body.HumansFinal result = new proto.Body.HumansFinal(this);
        int from_bitField0_ = bitField0_;
        if (bodyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            body_ = java.util.Collections.unmodifiableList(body_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.body_ = body_;
        } else {
          result.body_ = bodyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Body.HumansFinal) {
          return mergeFrom((proto.Body.HumansFinal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Body.HumansFinal other) {
        if (other == proto.Body.HumansFinal.getDefaultInstance()) return this;
        if (bodyBuilder_ == null) {
          if (!other.body_.isEmpty()) {
            if (body_.isEmpty()) {
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureBodyIsMutable();
              body_.addAll(other.body_);
            }
            onChanged();
          }
        } else {
          if (!other.body_.isEmpty()) {
            if (bodyBuilder_.isEmpty()) {
              bodyBuilder_.dispose();
              bodyBuilder_ = null;
              body_ = other.body_;
              bitField0_ = (bitField0_ & ~0x00000001);
              bodyBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBodyFieldBuilder() : null;
            } else {
              bodyBuilder_.addAllMessages(other.body_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Body.HumansFinal parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Body.HumansFinal) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.Body.Human> body_ =
        java.util.Collections.emptyList();
      private void ensureBodyIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          body_ = new java.util.ArrayList<proto.Body.Human>(body_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Body.Human, proto.Body.Human.Builder, proto.Body.HumanOrBuilder> bodyBuilder_;

      /**
       * <code>repeated .Human body = 1;</code>
       */
      public java.util.List<proto.Body.Human> getBodyList() {
        if (bodyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(body_);
        } else {
          return bodyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public int getBodyCount() {
        if (bodyBuilder_ == null) {
          return body_.size();
        } else {
          return bodyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public proto.Body.Human getBody(int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);
        } else {
          return bodyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public Builder setBody(
          int index, proto.Body.Human value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.set(index, value);
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public Builder setBody(
          int index, proto.Body.Human.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.set(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public Builder addBody(proto.Body.Human value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public Builder addBody(
          int index, proto.Body.Human value) {
        if (bodyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBodyIsMutable();
          body_.add(index, value);
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public Builder addBody(
          proto.Body.Human.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public Builder addBody(
          int index, proto.Body.Human.Builder builderForValue) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.add(index, builderForValue.build());
          onChanged();
        } else {
          bodyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public Builder addAllBody(
          java.lang.Iterable<? extends proto.Body.Human> values) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, body_);
          onChanged();
        } else {
          bodyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public Builder clearBody() {
        if (bodyBuilder_ == null) {
          body_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          bodyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public Builder removeBody(int index) {
        if (bodyBuilder_ == null) {
          ensureBodyIsMutable();
          body_.remove(index);
          onChanged();
        } else {
          bodyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public proto.Body.Human.Builder getBodyBuilder(
          int index) {
        return getBodyFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public proto.Body.HumanOrBuilder getBodyOrBuilder(
          int index) {
        if (bodyBuilder_ == null) {
          return body_.get(index);  } else {
          return bodyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public java.util.List<? extends proto.Body.HumanOrBuilder> 
           getBodyOrBuilderList() {
        if (bodyBuilder_ != null) {
          return bodyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(body_);
        }
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public proto.Body.Human.Builder addBodyBuilder() {
        return getBodyFieldBuilder().addBuilder(
            proto.Body.Human.getDefaultInstance());
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public proto.Body.Human.Builder addBodyBuilder(
          int index) {
        return getBodyFieldBuilder().addBuilder(
            index, proto.Body.Human.getDefaultInstance());
      }
      /**
       * <code>repeated .Human body = 1;</code>
       */
      public java.util.List<proto.Body.Human.Builder> 
           getBodyBuilderList() {
        return getBodyFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Body.Human, proto.Body.Human.Builder, proto.Body.HumanOrBuilder> 
          getBodyFieldBuilder() {
        if (bodyBuilder_ == null) {
          bodyBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.Body.Human, proto.Body.Human.Builder, proto.Body.HumanOrBuilder>(
                  body_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          body_ = null;
        }
        return bodyBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:HumansFinal)
    }

    // @@protoc_insertion_point(class_scope:HumansFinal)
    private static final proto.Body.HumansFinal DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Body.HumansFinal();
    }

    public static proto.Body.HumansFinal getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HumansFinal>
        PARSER = new com.google.protobuf.AbstractParser<HumansFinal>() {
      @java.lang.Override
      public HumansFinal parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HumansFinal(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HumansFinal> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HumansFinal> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Body.HumansFinal getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HumanOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Human)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string skeleton = 2;</code>
     * @return The skeleton.
     */
    java.lang.String getSkeleton();
    /**
     * <code>string skeleton = 2;</code>
     * @return The bytes for skeleton.
     */
    com.google.protobuf.ByteString
        getSkeletonBytes();

    /**
     * <code>string chrparams = 3;</code>
     * @return The chrparams.
     */
    java.lang.String getChrparams();
    /**
     * <code>string chrparams = 3;</code>
     * @return The bytes for chrparams.
     */
    com.google.protobuf.ByteString
        getChrparamsBytes();

    /**
     * <code>bool is_husk = 4;</code>
     * @return The isHusk.
     */
    boolean getIsHusk();

    /**
     * <code>string husk_head_name = 5;</code>
     * @return The huskHeadName.
     */
    java.lang.String getHuskHeadName();
    /**
     * <code>string husk_head_name = 5;</code>
     * @return The bytes for huskHeadName.
     */
    com.google.protobuf.ByteString
        getHuskHeadNameBytes();
  }
  /**
   * Protobuf type {@code Human}
   */
  public static final class Human extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Human)
      HumanOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Human.newBuilder() to construct.
    private Human(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Human() {
      name_ = "";
      skeleton_ = "";
      chrparams_ = "";
      huskHeadName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Human();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Human(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              skeleton_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              chrparams_ = s;
              break;
            }
            case 32: {

              isHusk_ = input.readBool();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              huskHeadName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Body.internal_static_Human_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Body.internal_static_Human_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Body.Human.class, proto.Body.Human.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SKELETON_FIELD_NUMBER = 2;
    private volatile java.lang.Object skeleton_;
    /**
     * <code>string skeleton = 2;</code>
     * @return The skeleton.
     */
    @java.lang.Override
    public java.lang.String getSkeleton() {
      java.lang.Object ref = skeleton_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        skeleton_ = s;
        return s;
      }
    }
    /**
     * <code>string skeleton = 2;</code>
     * @return The bytes for skeleton.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSkeletonBytes() {
      java.lang.Object ref = skeleton_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        skeleton_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHRPARAMS_FIELD_NUMBER = 3;
    private volatile java.lang.Object chrparams_;
    /**
     * <code>string chrparams = 3;</code>
     * @return The chrparams.
     */
    @java.lang.Override
    public java.lang.String getChrparams() {
      java.lang.Object ref = chrparams_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        chrparams_ = s;
        return s;
      }
    }
    /**
     * <code>string chrparams = 3;</code>
     * @return The bytes for chrparams.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChrparamsBytes() {
      java.lang.Object ref = chrparams_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chrparams_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IS_HUSK_FIELD_NUMBER = 4;
    private boolean isHusk_;
    /**
     * <code>bool is_husk = 4;</code>
     * @return The isHusk.
     */
    @java.lang.Override
    public boolean getIsHusk() {
      return isHusk_;
    }

    public static final int HUSK_HEAD_NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object huskHeadName_;
    /**
     * <code>string husk_head_name = 5;</code>
     * @return The huskHeadName.
     */
    @java.lang.Override
    public java.lang.String getHuskHeadName() {
      java.lang.Object ref = huskHeadName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        huskHeadName_ = s;
        return s;
      }
    }
    /**
     * <code>string husk_head_name = 5;</code>
     * @return The bytes for huskHeadName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHuskHeadNameBytes() {
      java.lang.Object ref = huskHeadName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        huskHeadName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getSkeletonBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, skeleton_);
      }
      if (!getChrparamsBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, chrparams_);
      }
      if (isHusk_ != false) {
        output.writeBool(4, isHusk_);
      }
      if (!getHuskHeadNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, huskHeadName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getSkeletonBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, skeleton_);
      }
      if (!getChrparamsBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, chrparams_);
      }
      if (isHusk_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isHusk_);
      }
      if (!getHuskHeadNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, huskHeadName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Body.Human)) {
        return super.equals(obj);
      }
      proto.Body.Human other = (proto.Body.Human) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getSkeleton()
          .equals(other.getSkeleton())) return false;
      if (!getChrparams()
          .equals(other.getChrparams())) return false;
      if (getIsHusk()
          != other.getIsHusk()) return false;
      if (!getHuskHeadName()
          .equals(other.getHuskHeadName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SKELETON_FIELD_NUMBER;
      hash = (53 * hash) + getSkeleton().hashCode();
      hash = (37 * hash) + CHRPARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getChrparams().hashCode();
      hash = (37 * hash) + IS_HUSK_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsHusk());
      hash = (37 * hash) + HUSK_HEAD_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getHuskHeadName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Body.Human parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Body.Human parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Body.Human parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Body.Human parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Body.Human parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Body.Human parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Body.Human parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Body.Human parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Body.Human parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Body.Human parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Body.Human parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Body.Human parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Body.Human prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Human}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Human)
        proto.Body.HumanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Body.internal_static_Human_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Body.internal_static_Human_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Body.Human.class, proto.Body.Human.Builder.class);
      }

      // Construct using proto.Body.Human.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        skeleton_ = "";

        chrparams_ = "";

        isHusk_ = false;

        huskHeadName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Body.internal_static_Human_descriptor;
      }

      @java.lang.Override
      public proto.Body.Human getDefaultInstanceForType() {
        return proto.Body.Human.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Body.Human build() {
        proto.Body.Human result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Body.Human buildPartial() {
        proto.Body.Human result = new proto.Body.Human(this);
        result.name_ = name_;
        result.skeleton_ = skeleton_;
        result.chrparams_ = chrparams_;
        result.isHusk_ = isHusk_;
        result.huskHeadName_ = huskHeadName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Body.Human) {
          return mergeFrom((proto.Body.Human)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Body.Human other) {
        if (other == proto.Body.Human.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getSkeleton().isEmpty()) {
          skeleton_ = other.skeleton_;
          onChanged();
        }
        if (!other.getChrparams().isEmpty()) {
          chrparams_ = other.chrparams_;
          onChanged();
        }
        if (other.getIsHusk() != false) {
          setIsHusk(other.getIsHusk());
        }
        if (!other.getHuskHeadName().isEmpty()) {
          huskHeadName_ = other.huskHeadName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Body.Human parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Body.Human) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object skeleton_ = "";
      /**
       * <code>string skeleton = 2;</code>
       * @return The skeleton.
       */
      public java.lang.String getSkeleton() {
        java.lang.Object ref = skeleton_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          skeleton_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string skeleton = 2;</code>
       * @return The bytes for skeleton.
       */
      public com.google.protobuf.ByteString
          getSkeletonBytes() {
        java.lang.Object ref = skeleton_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          skeleton_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string skeleton = 2;</code>
       * @param value The skeleton to set.
       * @return This builder for chaining.
       */
      public Builder setSkeleton(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        skeleton_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string skeleton = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkeleton() {
        
        skeleton_ = getDefaultInstance().getSkeleton();
        onChanged();
        return this;
      }
      /**
       * <code>string skeleton = 2;</code>
       * @param value The bytes for skeleton to set.
       * @return This builder for chaining.
       */
      public Builder setSkeletonBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        skeleton_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object chrparams_ = "";
      /**
       * <code>string chrparams = 3;</code>
       * @return The chrparams.
       */
      public java.lang.String getChrparams() {
        java.lang.Object ref = chrparams_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          chrparams_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string chrparams = 3;</code>
       * @return The bytes for chrparams.
       */
      public com.google.protobuf.ByteString
          getChrparamsBytes() {
        java.lang.Object ref = chrparams_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chrparams_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string chrparams = 3;</code>
       * @param value The chrparams to set.
       * @return This builder for chaining.
       */
      public Builder setChrparams(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        chrparams_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string chrparams = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearChrparams() {
        
        chrparams_ = getDefaultInstance().getChrparams();
        onChanged();
        return this;
      }
      /**
       * <code>string chrparams = 3;</code>
       * @param value The bytes for chrparams to set.
       * @return This builder for chaining.
       */
      public Builder setChrparamsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        chrparams_ = value;
        onChanged();
        return this;
      }

      private boolean isHusk_ ;
      /**
       * <code>bool is_husk = 4;</code>
       * @return The isHusk.
       */
      @java.lang.Override
      public boolean getIsHusk() {
        return isHusk_;
      }
      /**
       * <code>bool is_husk = 4;</code>
       * @param value The isHusk to set.
       * @return This builder for chaining.
       */
      public Builder setIsHusk(boolean value) {
        
        isHusk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_husk = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsHusk() {
        
        isHusk_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object huskHeadName_ = "";
      /**
       * <code>string husk_head_name = 5;</code>
       * @return The huskHeadName.
       */
      public java.lang.String getHuskHeadName() {
        java.lang.Object ref = huskHeadName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          huskHeadName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string husk_head_name = 5;</code>
       * @return The bytes for huskHeadName.
       */
      public com.google.protobuf.ByteString
          getHuskHeadNameBytes() {
        java.lang.Object ref = huskHeadName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          huskHeadName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string husk_head_name = 5;</code>
       * @param value The huskHeadName to set.
       * @return This builder for chaining.
       */
      public Builder setHuskHeadName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        huskHeadName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string husk_head_name = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHuskHeadName() {
        
        huskHeadName_ = getDefaultInstance().getHuskHeadName();
        onChanged();
        return this;
      }
      /**
       * <code>string husk_head_name = 5;</code>
       * @param value The bytes for huskHeadName to set.
       * @return This builder for chaining.
       */
      public Builder setHuskHeadNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        huskHeadName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Human)
    }

    // @@protoc_insertion_point(class_scope:Human)
    private static final proto.Body.Human DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Body.Human();
    }

    public static proto.Body.Human getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Human>
        PARSER = new com.google.protobuf.AbstractParser<Human>() {
      @java.lang.Override
      public Human parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Human(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Human> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Human> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Body.Human getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HumansFinal_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HumansFinal_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Human_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Human_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbody.proto\"#\n\013HumansFinal\022\024\n\004body\030\001 \003(" +
      "\0132\006.Human\"c\n\005Human\022\014\n\004name\030\001 \001(\t\022\020\n\010skel" +
      "eton\030\002 \001(\t\022\021\n\tchrparams\030\003 \001(\t\022\017\n\007is_husk" +
      "\030\004 \001(\010\022\026\n\016husk_head_name\030\005 \001(\tB\r\n\005protoB" +
      "\004Bodyb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_HumansFinal_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HumansFinal_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HumansFinal_descriptor,
        new java.lang.String[] { "Body", });
    internal_static_Human_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Human_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Human_descriptor,
        new java.lang.String[] { "Name", "Skeleton", "Chrparams", "IsHusk", "HuskHeadName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
