// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voice.proto

package proto;

public final class Voice {
  private Voice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DialogOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Dialog)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    java.util.List<proto.Voice.ActorVoice> 
        getActorVoiceLinesList();
    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    proto.Voice.ActorVoice getActorVoiceLines(int index);
    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    int getActorVoiceLinesCount();
    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    java.util.List<? extends proto.Voice.ActorVoiceOrBuilder> 
        getActorVoiceLinesOrBuilderList();
    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    proto.Voice.ActorVoiceOrBuilder getActorVoiceLinesOrBuilder(
        int index);
  }
  /**
   * <pre>
   * Organizes all dialog ids in the game.
   * </pre>
   *
   * Protobuf type {@code Dialog}
   */
  public static final class Dialog extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Dialog)
      DialogOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Dialog.newBuilder() to construct.
    private Dialog(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Dialog() {
      actorVoiceLines_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Dialog();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Dialog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                actorVoiceLines_ = new java.util.ArrayList<proto.Voice.ActorVoice>();
                mutable_bitField0_ |= 0x00000001;
              }
              actorVoiceLines_.add(
                  input.readMessage(proto.Voice.ActorVoice.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          actorVoiceLines_ = java.util.Collections.unmodifiableList(actorVoiceLines_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Voice.internal_static_Dialog_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Voice.internal_static_Dialog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Voice.Dialog.class, proto.Voice.Dialog.Builder.class);
    }

    public static final int ACTOR_VOICE_LINES_FIELD_NUMBER = 1;
    private java.util.List<proto.Voice.ActorVoice> actorVoiceLines_;
    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    @java.lang.Override
    public java.util.List<proto.Voice.ActorVoice> getActorVoiceLinesList() {
      return actorVoiceLines_;
    }
    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends proto.Voice.ActorVoiceOrBuilder> 
        getActorVoiceLinesOrBuilderList() {
      return actorVoiceLines_;
    }
    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    @java.lang.Override
    public int getActorVoiceLinesCount() {
      return actorVoiceLines_.size();
    }
    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    @java.lang.Override
    public proto.Voice.ActorVoice getActorVoiceLines(int index) {
      return actorVoiceLines_.get(index);
    }
    /**
     * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
     */
    @java.lang.Override
    public proto.Voice.ActorVoiceOrBuilder getActorVoiceLinesOrBuilder(
        int index) {
      return actorVoiceLines_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < actorVoiceLines_.size(); i++) {
        output.writeMessage(1, actorVoiceLines_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < actorVoiceLines_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, actorVoiceLines_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Voice.Dialog)) {
        return super.equals(obj);
      }
      proto.Voice.Dialog other = (proto.Voice.Dialog) obj;

      if (!getActorVoiceLinesList()
          .equals(other.getActorVoiceLinesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getActorVoiceLinesCount() > 0) {
        hash = (37 * hash) + ACTOR_VOICE_LINES_FIELD_NUMBER;
        hash = (53 * hash) + getActorVoiceLinesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Voice.Dialog parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Voice.Dialog parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Voice.Dialog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Voice.Dialog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Voice.Dialog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Voice.Dialog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Voice.Dialog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Voice.Dialog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Voice.Dialog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Voice.Dialog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Voice.Dialog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Voice.Dialog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Voice.Dialog prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Organizes all dialog ids in the game.
     * </pre>
     *
     * Protobuf type {@code Dialog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Dialog)
        proto.Voice.DialogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Voice.internal_static_Dialog_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Voice.internal_static_Dialog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Voice.Dialog.class, proto.Voice.Dialog.Builder.class);
      }

      // Construct using proto.Voice.Dialog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getActorVoiceLinesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (actorVoiceLinesBuilder_ == null) {
          actorVoiceLines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          actorVoiceLinesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Voice.internal_static_Dialog_descriptor;
      }

      @java.lang.Override
      public proto.Voice.Dialog getDefaultInstanceForType() {
        return proto.Voice.Dialog.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Voice.Dialog build() {
        proto.Voice.Dialog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Voice.Dialog buildPartial() {
        proto.Voice.Dialog result = new proto.Voice.Dialog(this);
        int from_bitField0_ = bitField0_;
        if (actorVoiceLinesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            actorVoiceLines_ = java.util.Collections.unmodifiableList(actorVoiceLines_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.actorVoiceLines_ = actorVoiceLines_;
        } else {
          result.actorVoiceLines_ = actorVoiceLinesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Voice.Dialog) {
          return mergeFrom((proto.Voice.Dialog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Voice.Dialog other) {
        if (other == proto.Voice.Dialog.getDefaultInstance()) return this;
        if (actorVoiceLinesBuilder_ == null) {
          if (!other.actorVoiceLines_.isEmpty()) {
            if (actorVoiceLines_.isEmpty()) {
              actorVoiceLines_ = other.actorVoiceLines_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureActorVoiceLinesIsMutable();
              actorVoiceLines_.addAll(other.actorVoiceLines_);
            }
            onChanged();
          }
        } else {
          if (!other.actorVoiceLines_.isEmpty()) {
            if (actorVoiceLinesBuilder_.isEmpty()) {
              actorVoiceLinesBuilder_.dispose();
              actorVoiceLinesBuilder_ = null;
              actorVoiceLines_ = other.actorVoiceLines_;
              bitField0_ = (bitField0_ & ~0x00000001);
              actorVoiceLinesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getActorVoiceLinesFieldBuilder() : null;
            } else {
              actorVoiceLinesBuilder_.addAllMessages(other.actorVoiceLines_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Voice.Dialog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Voice.Dialog) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.Voice.ActorVoice> actorVoiceLines_ =
        java.util.Collections.emptyList();
      private void ensureActorVoiceLinesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          actorVoiceLines_ = new java.util.ArrayList<proto.Voice.ActorVoice>(actorVoiceLines_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Voice.ActorVoice, proto.Voice.ActorVoice.Builder, proto.Voice.ActorVoiceOrBuilder> actorVoiceLinesBuilder_;

      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public java.util.List<proto.Voice.ActorVoice> getActorVoiceLinesList() {
        if (actorVoiceLinesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(actorVoiceLines_);
        } else {
          return actorVoiceLinesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public int getActorVoiceLinesCount() {
        if (actorVoiceLinesBuilder_ == null) {
          return actorVoiceLines_.size();
        } else {
          return actorVoiceLinesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public proto.Voice.ActorVoice getActorVoiceLines(int index) {
        if (actorVoiceLinesBuilder_ == null) {
          return actorVoiceLines_.get(index);
        } else {
          return actorVoiceLinesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public Builder setActorVoiceLines(
          int index, proto.Voice.ActorVoice value) {
        if (actorVoiceLinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActorVoiceLinesIsMutable();
          actorVoiceLines_.set(index, value);
          onChanged();
        } else {
          actorVoiceLinesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public Builder setActorVoiceLines(
          int index, proto.Voice.ActorVoice.Builder builderForValue) {
        if (actorVoiceLinesBuilder_ == null) {
          ensureActorVoiceLinesIsMutable();
          actorVoiceLines_.set(index, builderForValue.build());
          onChanged();
        } else {
          actorVoiceLinesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public Builder addActorVoiceLines(proto.Voice.ActorVoice value) {
        if (actorVoiceLinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActorVoiceLinesIsMutable();
          actorVoiceLines_.add(value);
          onChanged();
        } else {
          actorVoiceLinesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public Builder addActorVoiceLines(
          int index, proto.Voice.ActorVoice value) {
        if (actorVoiceLinesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActorVoiceLinesIsMutable();
          actorVoiceLines_.add(index, value);
          onChanged();
        } else {
          actorVoiceLinesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public Builder addActorVoiceLines(
          proto.Voice.ActorVoice.Builder builderForValue) {
        if (actorVoiceLinesBuilder_ == null) {
          ensureActorVoiceLinesIsMutable();
          actorVoiceLines_.add(builderForValue.build());
          onChanged();
        } else {
          actorVoiceLinesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public Builder addActorVoiceLines(
          int index, proto.Voice.ActorVoice.Builder builderForValue) {
        if (actorVoiceLinesBuilder_ == null) {
          ensureActorVoiceLinesIsMutable();
          actorVoiceLines_.add(index, builderForValue.build());
          onChanged();
        } else {
          actorVoiceLinesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public Builder addAllActorVoiceLines(
          java.lang.Iterable<? extends proto.Voice.ActorVoice> values) {
        if (actorVoiceLinesBuilder_ == null) {
          ensureActorVoiceLinesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, actorVoiceLines_);
          onChanged();
        } else {
          actorVoiceLinesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public Builder clearActorVoiceLines() {
        if (actorVoiceLinesBuilder_ == null) {
          actorVoiceLines_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          actorVoiceLinesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public Builder removeActorVoiceLines(int index) {
        if (actorVoiceLinesBuilder_ == null) {
          ensureActorVoiceLinesIsMutable();
          actorVoiceLines_.remove(index);
          onChanged();
        } else {
          actorVoiceLinesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public proto.Voice.ActorVoice.Builder getActorVoiceLinesBuilder(
          int index) {
        return getActorVoiceLinesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public proto.Voice.ActorVoiceOrBuilder getActorVoiceLinesOrBuilder(
          int index) {
        if (actorVoiceLinesBuilder_ == null) {
          return actorVoiceLines_.get(index);  } else {
          return actorVoiceLinesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public java.util.List<? extends proto.Voice.ActorVoiceOrBuilder> 
           getActorVoiceLinesOrBuilderList() {
        if (actorVoiceLinesBuilder_ != null) {
          return actorVoiceLinesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(actorVoiceLines_);
        }
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public proto.Voice.ActorVoice.Builder addActorVoiceLinesBuilder() {
        return getActorVoiceLinesFieldBuilder().addBuilder(
            proto.Voice.ActorVoice.getDefaultInstance());
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public proto.Voice.ActorVoice.Builder addActorVoiceLinesBuilder(
          int index) {
        return getActorVoiceLinesFieldBuilder().addBuilder(
            index, proto.Voice.ActorVoice.getDefaultInstance());
      }
      /**
       * <code>repeated .ActorVoice actor_voice_lines = 1;</code>
       */
      public java.util.List<proto.Voice.ActorVoice.Builder> 
           getActorVoiceLinesBuilderList() {
        return getActorVoiceLinesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.Voice.ActorVoice, proto.Voice.ActorVoice.Builder, proto.Voice.ActorVoiceOrBuilder> 
          getActorVoiceLinesFieldBuilder() {
        if (actorVoiceLinesBuilder_ == null) {
          actorVoiceLinesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.Voice.ActorVoice, proto.Voice.ActorVoice.Builder, proto.Voice.ActorVoiceOrBuilder>(
                  actorVoiceLines_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          actorVoiceLines_ = null;
        }
        return actorVoiceLinesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Dialog)
    }

    // @@protoc_insertion_point(class_scope:Dialog)
    private static final proto.Voice.Dialog DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Voice.Dialog();
    }

    public static proto.Voice.Dialog getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Dialog>
        PARSER = new com.google.protobuf.AbstractParser<Dialog>() {
      @java.lang.Override
      public Dialog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Dialog(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Dialog> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Dialog> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Voice.Dialog getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActorVoiceOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ActorVoice)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string actor_id = 1;</code>
     * @return The actorId.
     */
    java.lang.String getActorId();
    /**
     * <code>string actor_id = 1;</code>
     * @return The bytes for actorId.
     */
    com.google.protobuf.ByteString
        getActorIdBytes();

    /**
     * <code>repeated string voice_lines = 2;</code>
     * @return A list containing the voiceLines.
     */
    java.util.List<java.lang.String>
        getVoiceLinesList();
    /**
     * <code>repeated string voice_lines = 2;</code>
     * @return The count of voiceLines.
     */
    int getVoiceLinesCount();
    /**
     * <code>repeated string voice_lines = 2;</code>
     * @param index The index of the element to return.
     * @return The voiceLines at the given index.
     */
    java.lang.String getVoiceLines(int index);
    /**
     * <code>repeated string voice_lines = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the voiceLines at the given index.
     */
    com.google.protobuf.ByteString
        getVoiceLinesBytes(int index);
  }
  /**
   * <pre>
   * All dialog for a particular actor.
   * </pre>
   *
   * Protobuf type {@code ActorVoice}
   */
  public static final class ActorVoice extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ActorVoice)
      ActorVoiceOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ActorVoice.newBuilder() to construct.
    private ActorVoice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ActorVoice() {
      actorId_ = "";
      voiceLines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ActorVoice();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ActorVoice(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              actorId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                voiceLines_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              voiceLines_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          voiceLines_ = voiceLines_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.Voice.internal_static_ActorVoice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.Voice.internal_static_ActorVoice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.Voice.ActorVoice.class, proto.Voice.ActorVoice.Builder.class);
    }

    public static final int ACTOR_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object actorId_;
    /**
     * <code>string actor_id = 1;</code>
     * @return The actorId.
     */
    @java.lang.Override
    public java.lang.String getActorId() {
      java.lang.Object ref = actorId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actorId_ = s;
        return s;
      }
    }
    /**
     * <code>string actor_id = 1;</code>
     * @return The bytes for actorId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActorIdBytes() {
      java.lang.Object ref = actorId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actorId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VOICE_LINES_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList voiceLines_;
    /**
     * <code>repeated string voice_lines = 2;</code>
     * @return A list containing the voiceLines.
     */
    public com.google.protobuf.ProtocolStringList
        getVoiceLinesList() {
      return voiceLines_;
    }
    /**
     * <code>repeated string voice_lines = 2;</code>
     * @return The count of voiceLines.
     */
    public int getVoiceLinesCount() {
      return voiceLines_.size();
    }
    /**
     * <code>repeated string voice_lines = 2;</code>
     * @param index The index of the element to return.
     * @return The voiceLines at the given index.
     */
    public java.lang.String getVoiceLines(int index) {
      return voiceLines_.get(index);
    }
    /**
     * <code>repeated string voice_lines = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the voiceLines at the given index.
     */
    public com.google.protobuf.ByteString
        getVoiceLinesBytes(int index) {
      return voiceLines_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getActorIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, actorId_);
      }
      for (int i = 0; i < voiceLines_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, voiceLines_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getActorIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, actorId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < voiceLines_.size(); i++) {
          dataSize += computeStringSizeNoTag(voiceLines_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getVoiceLinesList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.Voice.ActorVoice)) {
        return super.equals(obj);
      }
      proto.Voice.ActorVoice other = (proto.Voice.ActorVoice) obj;

      if (!getActorId()
          .equals(other.getActorId())) return false;
      if (!getVoiceLinesList()
          .equals(other.getVoiceLinesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getActorId().hashCode();
      if (getVoiceLinesCount() > 0) {
        hash = (37 * hash) + VOICE_LINES_FIELD_NUMBER;
        hash = (53 * hash) + getVoiceLinesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.Voice.ActorVoice parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Voice.ActorVoice parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Voice.ActorVoice parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Voice.ActorVoice parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Voice.ActorVoice parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.Voice.ActorVoice parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.Voice.ActorVoice parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Voice.ActorVoice parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Voice.ActorVoice parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.Voice.ActorVoice parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.Voice.ActorVoice parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.Voice.ActorVoice parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.Voice.ActorVoice prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * All dialog for a particular actor.
     * </pre>
     *
     * Protobuf type {@code ActorVoice}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ActorVoice)
        proto.Voice.ActorVoiceOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.Voice.internal_static_ActorVoice_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.Voice.internal_static_ActorVoice_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.Voice.ActorVoice.class, proto.Voice.ActorVoice.Builder.class);
      }

      // Construct using proto.Voice.ActorVoice.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        actorId_ = "";

        voiceLines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.Voice.internal_static_ActorVoice_descriptor;
      }

      @java.lang.Override
      public proto.Voice.ActorVoice getDefaultInstanceForType() {
        return proto.Voice.ActorVoice.getDefaultInstance();
      }

      @java.lang.Override
      public proto.Voice.ActorVoice build() {
        proto.Voice.ActorVoice result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.Voice.ActorVoice buildPartial() {
        proto.Voice.ActorVoice result = new proto.Voice.ActorVoice(this);
        int from_bitField0_ = bitField0_;
        result.actorId_ = actorId_;
        if (((bitField0_ & 0x00000001) != 0)) {
          voiceLines_ = voiceLines_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.voiceLines_ = voiceLines_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.Voice.ActorVoice) {
          return mergeFrom((proto.Voice.ActorVoice)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.Voice.ActorVoice other) {
        if (other == proto.Voice.ActorVoice.getDefaultInstance()) return this;
        if (!other.getActorId().isEmpty()) {
          actorId_ = other.actorId_;
          onChanged();
        }
        if (!other.voiceLines_.isEmpty()) {
          if (voiceLines_.isEmpty()) {
            voiceLines_ = other.voiceLines_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVoiceLinesIsMutable();
            voiceLines_.addAll(other.voiceLines_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.Voice.ActorVoice parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.Voice.ActorVoice) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object actorId_ = "";
      /**
       * <code>string actor_id = 1;</code>
       * @return The actorId.
       */
      public java.lang.String getActorId() {
        java.lang.Object ref = actorId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          actorId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string actor_id = 1;</code>
       * @return The bytes for actorId.
       */
      public com.google.protobuf.ByteString
          getActorIdBytes() {
        java.lang.Object ref = actorId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actorId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string actor_id = 1;</code>
       * @param value The actorId to set.
       * @return This builder for chaining.
       */
      public Builder setActorId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        actorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string actor_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearActorId() {
        
        actorId_ = getDefaultInstance().getActorId();
        onChanged();
        return this;
      }
      /**
       * <code>string actor_id = 1;</code>
       * @param value The bytes for actorId to set.
       * @return This builder for chaining.
       */
      public Builder setActorIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        actorId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList voiceLines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureVoiceLinesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          voiceLines_ = new com.google.protobuf.LazyStringArrayList(voiceLines_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string voice_lines = 2;</code>
       * @return A list containing the voiceLines.
       */
      public com.google.protobuf.ProtocolStringList
          getVoiceLinesList() {
        return voiceLines_.getUnmodifiableView();
      }
      /**
       * <code>repeated string voice_lines = 2;</code>
       * @return The count of voiceLines.
       */
      public int getVoiceLinesCount() {
        return voiceLines_.size();
      }
      /**
       * <code>repeated string voice_lines = 2;</code>
       * @param index The index of the element to return.
       * @return The voiceLines at the given index.
       */
      public java.lang.String getVoiceLines(int index) {
        return voiceLines_.get(index);
      }
      /**
       * <code>repeated string voice_lines = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the voiceLines at the given index.
       */
      public com.google.protobuf.ByteString
          getVoiceLinesBytes(int index) {
        return voiceLines_.getByteString(index);
      }
      /**
       * <code>repeated string voice_lines = 2;</code>
       * @param index The index to set the value at.
       * @param value The voiceLines to set.
       * @return This builder for chaining.
       */
      public Builder setVoiceLines(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVoiceLinesIsMutable();
        voiceLines_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string voice_lines = 2;</code>
       * @param value The voiceLines to add.
       * @return This builder for chaining.
       */
      public Builder addVoiceLines(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureVoiceLinesIsMutable();
        voiceLines_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string voice_lines = 2;</code>
       * @param values The voiceLines to add.
       * @return This builder for chaining.
       */
      public Builder addAllVoiceLines(
          java.lang.Iterable<java.lang.String> values) {
        ensureVoiceLinesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, voiceLines_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string voice_lines = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVoiceLines() {
        voiceLines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string voice_lines = 2;</code>
       * @param value The bytes of the voiceLines to add.
       * @return This builder for chaining.
       */
      public Builder addVoiceLinesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureVoiceLinesIsMutable();
        voiceLines_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ActorVoice)
    }

    // @@protoc_insertion_point(class_scope:ActorVoice)
    private static final proto.Voice.ActorVoice DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.Voice.ActorVoice();
    }

    public static proto.Voice.ActorVoice getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ActorVoice>
        PARSER = new com.google.protobuf.AbstractParser<ActorVoice>() {
      @java.lang.Override
      public ActorVoice parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ActorVoice(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ActorVoice> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ActorVoice> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.Voice.ActorVoice getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dialog_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dialog_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ActorVoice_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ActorVoice_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013voice.proto\"0\n\006Dialog\022&\n\021actor_voice_l" +
      "ines\030\001 \003(\0132\013.ActorVoice\"3\n\nActorVoice\022\020\n" +
      "\010actor_id\030\001 \001(\t\022\023\n\013voice_lines\030\002 \003(\tB\016\n\005" +
      "protoB\005Voiceb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Dialog_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Dialog_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dialog_descriptor,
        new java.lang.String[] { "ActorVoiceLines", });
    internal_static_ActorVoice_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ActorVoice_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ActorVoice_descriptor,
        new java.lang.String[] { "ActorId", "VoiceLines", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
